module SkelPascal where

-- Haskell module generated by the BNF converter

import AbsPascal
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transProgram :: Program -> Result
transProgram x = case x of
  PBlock ident varpart defs stms -> failure x
transType :: Type -> Result
transType x = case x of
  Type_bool -> failure x
  Type_integer -> failure x
  Type_char -> failure x
  Type_real -> failure x
  Type_string -> failure x
transVarPart :: VarPart -> Result
transVarPart x = case x of
  VPart vardecls -> failure x
  VPartEmpty -> failure x
transVarDecl :: VarDecl -> Result
transVarDecl x = case x of
  VDecl idents type_ -> failure x
transDef :: Def -> Result
transDef x = case x of
  DProc ident params varpart stms -> failure x
  DFun ident params type_ varpart stms -> failure x
transParam :: Param -> Result
transParam x = case x of
  ParamSingle idents type_ -> failure x
  ParamRef idents type_ -> failure x
transStm :: Stm -> Result
transStm x = case x of
  SAss ident exp -> failure x
  SCall ident exps -> failure x
  SCallEmpty ident -> failure x
  SRepeat stm exp -> failure x
  SWhile exp stm -> failure x
  SBlock stms -> failure x
  SFor ident exp1 exp2 stm -> failure x
  SIf exp stm1 stm2 -> failure x
  SEmpty -> failure x
transExp :: Exp -> Result
transExp x = case x of
  EEq exp1 exp2 -> failure x
  EDiff exp1 exp2 -> failure x
  ELe exp1 exp2 -> failure x
  ELeq exp1 exp2 -> failure x
  EGeq exp1 exp2 -> failure x
  EGe exp1 exp2 -> failure x
  EPlus exp1 exp2 -> failure x
  ESubst exp1 exp2 -> failure x
  EOr exp1 exp2 -> failure x
  EMul exp1 exp2 -> failure x
  EDiv exp1 exp2 -> failure x
  EAnd exp1 exp2 -> failure x
  EMod exp1 exp2 -> failure x
  EDiv2 exp1 exp2 -> failure x
  ECall ident exps -> failure x
  ECallEmpty ident -> failure x
  EStr string -> failure x
  EInt integer -> failure x
  EReal double -> failure x
  EChar char -> failure x
  ETrue -> failure x
  EFalse -> failure x
  EIdent ident -> failure x
  ENot exp -> failure x
  ENegNum exp -> failure x
  EPlusNum exp -> failure x

